#ifndef RA_DEFINITIONS_H
#define RA_DEFINITIONS_H

enum BANDWIDTH{
  BANDWIDTH_7K8,
  BANDWIDTH_10K4,
  BANDWIDTH_15K6,
  BANDWIDTH_20K8,
  BANDWIDTH_31K25,
  BANDWIDTH_41K7,
  BANDWIDTH_62K5,
  BANDWIDTH_125K,
  BANDWIDTH_250K,
  BANDWIDTH_500K
};

enum CODING_RATE{
  CODING_RATE_5,
  CODING_RATE_6,
  CODING_RATE_7,
  CODING_RATE_8
};

enum SPREADING_FACTOR{
  SPREADING_FACTOR_6,
  SPREADING_FACTOR_7,
  SPREADING_FACTOR_8,
  SPREADING_FACTOR_9,
  SPREADING_FACTOR_10,
  SPREADING_FACTOR_11,
  SPREADING_FACTOR_12
};

enum TX_POWER{
  TX_POWER_2,
  TX_POWER_3,
  TX_POWER_4,
  TX_POWER_5,
  TX_POWER_6,
  TX_POWER_7,
  TX_POWER_8,
  TX_POWER_9,
  TX_POWER_10,
  TX_POWER_11,
  TX_POWER_12,
  TX_POWER_13,
  TX_POWER_14,
  TX_POWER_15,
  TX_POWER_16,
  TX_POWER_17,
  TX_POWER_18,
  TX_POWER_19,
  TX_POWER_20
};

#endif